--- 
services:
  - docker
before_install: 
  - "wget https://github.com/instrumenta/kubeval/releases/download/0.9.2/kubeval-linux-amd64.tar.gz"
  - "tar xzvf kubeval-linux-amd64.tar.gz"
  - "chmod +x kubeval"
jobs: 
  include:
    - script: ./run_kubeval.sh
      stage: test
    - script: ./run_kubesec.sh
      stage: security
language: C
sudo: false

