apiVersion: v1
kind: Service
metadata:
  labels:
    run: standalone-chrome
  name: standalone-chrome-service
  namespace: comments-scraper
spec:
  ports:
  - port: 4444
    protocol: TCP
    targetPort: 4444
  selector:
    run: standalone-chrome
  type: ClusterIP
